version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "TestConnectionPass123!"
      ACCEPT_EULA: "Y"

  movies.accounts.api:
    image: ${DOCKER_REGISTRY-}moviesaccountsapi
    build:
      context: .
      dockerfile: Movies.Accounts.Api/Dockerfile

  movies.client.api:
    image: ${DOCKER_REGISTRY-}moviesclientapi
    build:
      context: .
      dockerfile: Movies.Client.Api/Dockerfile

  movies.admin.api:
    image: ${DOCKER_REGISTRY-}moviesadminapi
    build:
      context: .
      dockerfile: Movies.Admin.Api/Dockerfile

  dbfillerapp:
    image: ${DOCKER_REGISTRY-}dbfillerapp
    build:
      context: .
      dockerfile: DbFillerApp/Dockerfile

