version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "TestConnectionPass123!"
      ACCEPT_EULA: "Y"

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data

  movies.accounts.api:
    image: ${DOCKER_REGISTRY-}moviesaccountsapi
    build:
      context: .
      dockerfile: Movies.Accounts.Api/Dockerfile

  movies.client.api:
    image: ${DOCKER_REGISTRY-}moviesclientapi
    build:
      context: .
      dockerfile: Movies.Client.Api/Dockerfile

  movies.admin.api:
    image: ${DOCKER_REGISTRY-}moviesadminapi
    build:
      context: .
      dockerfile: Movies.Admin.Api/Dockerfile

  dbfillerapp:
    image: ${DOCKER_REGISTRY-}dbfillerapp
    build:
      context: .
      dockerfile: DbFillerApp/Dockerfile


volumes:
  cache:
    driver: local